### ISSUE TITLE
'Duplicate Signature' errors

### ISSUE THREAD

**Issue by matthai** [tkf/emacs-ipython-notebook#134]
Hi,
First of all, thanks for creating EIN. It's brilliant and completely changed the way I work.

I've been using EIN for about 5 months now, using Windows 8.1/WinPython + MSYS + emacs 24.3.1. I run everything locally on a desktop.

Over the past months, I have started getting messages like this when I commands in the notebook from within EIN (I can interact with the same notebook on the same kernel from a browser without any problem at all). 

--- Message copied from within emacs EIN buffer ---
ERROR:IPKernelApp:Invalid Message
Traceback (most recent call last):
  File "d:\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\IPython\zmq\ipkernel.py", line 201, in dispatch_shell
    msg = self.session.unserialize(msg, content=True, copy=False)
  File "d:\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\IPython\zmq\session.py", line 721, in unserialize
    raise ValueError("Duplicate Signature: %r"%signature)
ValueError: Duplicate Signature: 'e5e94f0e7c96d35179384594a2f012f2'
--- EIN message end ---

I run ipython from an msys bash shell, like this (I have included a couple of "duplicate signature" error messages in case it's useful) :
---- bash output begin ---
$ ipython notebook --pylab inline fire.ipynb
[NotebookApp] Using existing profile dir: u'd:\matthai\.ipython\profile_default'
[NotebookApp] Serving notebooks from d:\matthai\projects\cmi\fire\src\python\fire [NotebookApp] The IPython Notebook is running at: http://127.0.0.1:8888/
[NotebookApp] Use Control-C to stop this server and shut down all kernels.
[NotebookApp] Using MathJax from CDN: http://cdn.mathjax.org/mathjax/latest/MathJax.js
[NotebookApp] Kernel started: b18dc1f5-f083-4990-8b05-995c48771b1b
[IPKernelApp] To connect another client to this kernel, use:
[IPKernelApp] --existing kernel-b18dc1f5-f083-4990-8b05-995c48771b1b.json
[NotebookApp] Connecting to: tcp://127.0.0.1:51651
[NotebookApp] Connecting to: tcp://127.0.0.1:51652
[NotebookApp] Connecting to: tcp://127.0.0.1:51654
[NotebookApp] Kernel interrupted: b18dc1f5-f083-4990-8b05-995c48771b1b
[NotebookApp] Using existing kernel: b18dc1f5-f083-4990-8b05-995c48771b1b
[NotebookApp] Connecting to: tcp://127.0.0.1:51651
[NotebookApp] Connecting to: tcp://127.0.0.1:51652
[NotebookApp] Connecting to: tcp://127.0.0.1:51654
[IPKernelApp] Invalid Message
Traceback (most recent call last):
  File "d:\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\IPython\zmq\ipkernel.py", line 201, in dispatch_shell
    msg = self.session.unserialize(msg, content=True, copy=False)
  File "d:\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\IPython\zmq\session.py", line 721, in unserialize
    raise ValueError("Duplicate Signature: %r"%signature)
ValueError: Duplicate Signature: '122ae9f658b00885581de14c41d3d00e'
[IPKernelApp] Invalid Message
Traceback (most recent call last):
  File "d:\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\IPython\zmq\ipkernel.py", line 201, in dispatch_shell
    msg = self.session.unserialize(msg, content=True, copy=False)
  File "d:\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\IPython\zmq\session.py", line 721, in unserialize
    raise ValueError("Duplicate Signature: %r"%signature)
ValueError: Duplicate Signature: '7ddb4430d4a11bb8cfc374c566ce554d'
---- bash output end ---

Any idea what the problem may be?
           Thanks!

**Comment by het90** [comment]
Did you find a fix for this issue? I've been getting the same error and wanted to dive deeper into the cause.
